b# TOPIC: predicting topics of hotel reviews data

#1 / Loading data

In [1]:
import pandas as pd

data = pd.read_csv("DATA/Text_Cluster/7282_1.csv")
print(data.info())
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35912 entries, 0 to 35911
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   address               35912 non-null  object 
 1   categories            35912 non-null  object 
 2   city                  35912 non-null  object 
 3   country               35912 non-null  object 
 4   latitude              35826 non-null  float64
 5   longitude             35826 non-null  float64
 6   name                  35912 non-null  object 
 7   postalCode            35857 non-null  object 
 8   province              35912 non-null  object 
 9   reviews.date          35653 non-null  object 
 10  reviews.dateAdded     35912 non-null  object 
 11  reviews.doRecommend   0 non-null      float64
 12  reviews.id            0 non-null      float64
 13  reviews.rating        35050 non-null  float64
 14  reviews.text          35890 non-null  object 
 15  reviews.title      

address categories      city country   latitude  longitude  \
0  Riviera San Nicol 11/a     Hotels  Mableton      US  45.421611  12.376187   
1  Riviera San Nicol 11/a     Hotels  Mableton      US  45.421611  12.376187   
2  Riviera San Nicol 11/a     Hotels  Mableton      US  45.421611  12.376187   
3  Riviera San Nicol 11/a     Hotels  Mableton      US  45.421611  12.376187   
4  Riviera San Nicol 11/a     Hotels  Mableton      US  45.421611  12.376187   

                 name postalCode province          reviews.date  \
0  Hotel Russo Palace      30126       GA  2013-09-22T00:00:00Z   
1  Hotel Russo Palace      30126       GA  2015-04-03T00:00:00Z   
2  Hotel Russo Palace      30126       GA  2014-05-13T00:00:00Z   
3  Hotel Russo Palace      30126       GA  2013-10-27T00:00:00Z   
4  Hotel Russo Palace      30126       GA  2015-03-05T00:00:00Z   

      reviews.dateAdded  reviews.doRecommend  reviews.id  reviews.rating  \
0  2016-10-24T00:00:25Z                  NaN         NaN             4.0   
1  2016-10-24T00:00:25Z                  NaN         NaN             5.0   
2  2016-10-24T00:00:25Z                  NaN         NaN             5.0   
3  2016-10-24T00:00:25Z                  NaN         NaN             5.0   
4  2016-10-24T00:00:25Z                  NaN         NaN             5.0   

                                        reviews.text  \
0  Pleasant 10 min walk along the sea front to th...   
1  Really lovely hotel. Stayed on the very top fl...   
2  Ett mycket bra hotell. Det som drog ner betyge...   
3  We stayed here for four nights in October. The...   
4  We stayed here for four nights in October. The...   

                        reviews.title reviews.userCity reviews.username  \
0  Good location away from the crouds              NaN      Russ (kent)   
1      Great hotel with Jacuzzi bath!              NaN       A Traveler   
2                         Lugnt l��ge              NaN             Maud   
3          Good location on the Lido.              NaN            Julie   
4              ������ ���������������              NaN         sungchul   

  reviews.userProvince  
0                  NaN  
1                  NaN  
2                  NaN  
3                  NaN  
4                  NaN

# 2/ Exploring data

In [2]:
# edit columns names
data.columns = data.columns.str.strip().str.lower().str.replace('.', '_')
print(data.info())
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35912 entries, 0 to 35911
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   address               35912 non-null  object 
 1   categories            35912 non-null  object 
 2   city                  35912 non-null  object 
 3   country               35912 non-null  object 
 4   latitude              35826 non-null  float64
 5   longitude             35826 non-null  float64
 6   name                  35912 non-null  object 
 7   postalcode            35857 non-null  object 
 8   province              35912 non-null  object 
 9   reviews_date          35653 non-null  object 
 10  reviews_dateadded     35912 non-null  object 
 11  reviews_dorecommend   0 non-null      float64
 12  reviews_id            0 non-null      float64
 13  reviews_rating        35050 non-null  float64
 14  reviews_text          35890 non-null  object 
 15  reviews_title      

address categories      city country   latitude  longitude  \
0  Riviera San Nicol 11/a     Hotels  Mableton      US  45.421611  12.376187   
1  Riviera San Nicol 11/a     Hotels  Mableton      US  45.421611  12.376187   
2  Riviera San Nicol 11/a     Hotels  Mableton      US  45.421611  12.376187   
3  Riviera San Nicol 11/a     Hotels  Mableton      US  45.421611  12.376187   
4  Riviera San Nicol 11/a     Hotels  Mableton      US  45.421611  12.376187   

                 name postalcode province          reviews_date  \
0  Hotel Russo Palace      30126       GA  2013-09-22T00:00:00Z   
1  Hotel Russo Palace      30126       GA  2015-04-03T00:00:00Z   
2  Hotel Russo Palace      30126       GA  2014-05-13T00:00:00Z   
3  Hotel Russo Palace      30126       GA  2013-10-27T00:00:00Z   
4  Hotel Russo Palace      30126       GA  2015-03-05T00:00:00Z   

      reviews_dateadded  reviews_dorecommend  reviews_id  reviews_rating  \
0  2016-10-24T00:00:25Z                  NaN         NaN             4.0   
1  2016-10-24T00:00:25Z                  NaN         NaN             5.0   
2  2016-10-24T00:00:25Z                  NaN         NaN             5.0   
3  2016-10-24T00:00:25Z                  NaN         NaN             5.0   
4  2016-10-24T00:00:25Z                  NaN         NaN             5.0   

                                        reviews_text  \
0  Pleasant 10 min walk along the sea front to th...   
1  Really lovely hotel. Stayed on the very top fl...   
2  Ett mycket bra hotell. Det som drog ner betyge...   
3  We stayed here for four nights in October. The...   
4  We stayed here for four nights in October. The...   

                        reviews_title reviews_usercity reviews_username  \
0  Good location away from the crouds              NaN      Russ (kent)   
1      Great hotel with Jacuzzi bath!              NaN       A Traveler   
2                         Lugnt l��ge              NaN             Maud   
3          Good location on the Lido.              NaN            Julie   
4              ������ ���������������              NaN         sungchul   

  reviews_userprovince  
0                  NaN  
1                  NaN  
2                  NaN  
3                  NaN  
4                  NaN

In [124]:
import numpy as np
# array of review_texts
texts = np.array(data['reviews_text'].astype(str))
texts.shape

(35912,)

"Pleasant 10 min walk along the sea front to the Water Bus. restaurants etc. Hotel was comfortable breakfast was good - quite a variety. Room aircon didn't work very well. Take mosquito repelant!"

In [60]:
import nltk
nltk.download('punkt')
from nltk import sent_tokenize
from functools import reduce
import numpy as np

# tokenize each element (comment) in the texts into sentences: list of lists
token_texts = list(map(lambda x: sent_tokenize(str(x)),texts))

# put all sentences together as one array
sentences = np.array(reduce(lambda x,y: x+y,token_texts))
print("sentences.shape = ", sentences.shape)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\zacha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


(138301,)

# 3/ Latent Semantic Analysis (LSA)
- Creating document-term matrix: using TfidfVectorizer
- Extracting features: using TruncatedSVD (for spare matrix)

In [72]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import Normalizer
lsa = Pipeline([("tfidf",TfidfVectorizer(ngram_range=(1,2),stop_words='english')),
                 ("svd",TruncatedSVD(n_components=20)),
                 ("normalizer",Normalizer())])
lsa_sentences = lsa.fit_transform(sentences)
lsa_sentences.shape

(138301, 20)

# 4/ Unsupervised model: KMeans

In [73]:
from sklearn.cluster import KMeans
cluster = KMeans(n_clusters=10)
cluster.fit(lsa_sentences)


KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=10, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [75]:
cluster_predicted = cluster.predict(lsa_sentences)
cluster_predicted


array([0, 9, 5, ..., 9, 0, 9])

In [76]:
from collections import Counter
Counter(cluster_predicted)



Counter({0: 35217,
         9: 19339,
         5: 8668,
         6: 12763,
         8: 12124,
         3: 17876,
         4: 9644,
         7: 7706,
         1: 6687,
         2: 8277})

In [85]:
centroids = cluster.cluster_centers_

In [86]:
original_centroids = lsa.steps[1][1].inverse_transform(centroids)

In [87]:
original_centroids_ordered = original_centroids.argsort()[:, ::-1]

In [84]:
terms = lsa.steps[0][1].get_feature_names()
terms

['00',
 '00 01',
 '00 125',
 '00 150',
 '00 20',
 '00 24',
 '00 30',
 '00 600',
 '00 additional',
 '00 adult',
 '00 arrival',
 '00 arrived',
 '00 asked',
 '00 bed',
 '00 bedroom',
 '00 beginning',
 '00 believe',
 '00 better',
 '00 big',
 '00 booking',
 '00 bottle',
 '00 bowl',
 '00 breakfast',
 '00 buffet',
 '00 cash',
 '00 catch',
 '00 ceramic',
 '00 champagne',
 '00 charge',
 '00 cheaper',
 '00 check',
 '00 checked',
 '00 checkout',
 '00 child',
 '00 children',
 '00 cleaning',
 '00 coffee',
 '00 collapsed',
 '00 compared',
 '00 comping',
 '00 couldn',
 '00 credit',
 '00 day',
 '00 days',
 '00 dear',
 '00 decided',
 '00 deposit',
 '00 did',
 '00 didn',
 '00 dinner',
 '00 discount',
 '00 displeased',
 '00 dog',
 '00 dollar',
 '00 dollars',
 '00 door',
 '00 dress',
 '00 drinking',
 '00 driving',
 '00 du',
 '00 early',
 '00 effort',
 '00 entire',
 '00 etwas',
 '00 euro',
 '00 event',
 '00 expect',
 '00 fantastic',
 '00 fee',
 '00 fish',
 '00 friday',
 '00 gift',
 '00 going',
 '00 got',
 

In [97]:
for i in range(10):
    print(f"Cluster = {i}:     ",end='')
    for j in range(5):
        print(f"{terms[original_centroids_ordered[i,j]]}, ", end='')
    print()


Cluster = 0:     rooms, room, enjoyed, stayed, hotel, 
Cluster = 1:     nice, nice hotel, room, hotel, nice clean, 
Cluster = 2:     stay, hotel, definitely stay, enjoyed, enjoyed stay, 
Cluster = 3:     stayed, night, nights, stayed night, hotel, 
Cluster = 4:     staff, friendly, helpful, staff friendly, friendly staff, 
Cluster = 5:     breakfast, breakfast good, free, free breakfast, breakfast great, 
Cluster = 6:     room, room clean, room nice, rooms, spacious, 
Cluster = 7:     great, location, great location, hotel, great stay, 
Cluster = 8:     hotel, hotel clean, nice hotel, great hotel, hotel staff, 
Cluster = 9:     good, clean, comfortable, location, place, 


In [89]:
original_centroids_ordered.shape



(10, 345451)

In [90]:
original_centroids_ordered[0]



array([258809, 256154, 100207, ..., 256697,  56687,  56840], dtype=int64)

In [91]:
original_centroids[0]

array([ 5.43507136e-03,  8.61442626e-05,  1.75228432e-05, ...,
       -3.91242520e-14, -1.47991918e-15, -1.47991918e-15])

In [99]:
texts.shape

(35912,)

In [125]:
import sys
sys.path.insert(1,'E:\DUY\DS\deeplearning\CustomTools')
import natural_language_processing_tools as nlpt
texts_cleaned = nlpt.normalize_corpus(texts,html_stripping=False)


In [115]:
type(texts)


numpy.ndarray

In [134]:
type(texts_cleaned)


list

In [135]:
texts_cleaned[0]

'pleasant 10 min walk along sea front water bus restaurant etc hotel comfortable breakfast good quite variety room aircon not work well take mosquito repelant'